jobs:
- job: ManyLinux1Wheel
  pool: {vmImage: 'Ubuntu-16.04'}
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - script: |
      docker pull quay.io/pypa/manylinux1_x86_64
      docker run --rm -v $PWD:/io quay.io/pypa/manylinux1_x86_64 /io/build-wheels.sh
      mkdir wheelhouse
      sudo mv dist/*manylinux1*.whl wheelhouse
    displayName: Build manylinux1 wheel
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: wheelhouse
      artifactName: Wheels
